mysql:
  image: hypriot/rpi-mysql
  container_name: mysql
  tty: false
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: test
    MYSQL_USER: test
    MYSQL_PASSWORD: test
    MYSQL_ROOT_PASSWORD: test
    SERVICE_TAGS: dev
    SERVICE_NAME: mysql
