version: "3.9"

services:
  db:
    platform: linux/x86_64
    image: mysql:8
    container_name: massage-star-db
    environment:
      - "MYSQL_DATABASE=test"
      - "MYSQL_USER=test"
      - "MYSQL_PASSWORD=test"
    ports:
      - "3306:3306"
